services:
  app:
    build:
      context: .
      dockerfile: Docker/app/Dockerfile
    container_name: trax_lrs_app
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: trax
      DB_USERNAME: traxuser
      DB_PASSWORD: traxpass

  nginx:
    image: nginx:latest
    container_name: trax_lrs_nginx
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: trax_lrs_db
    restart: always
    environment:
      POSTGRES_DB: trax
      POSTGRES_USER: traxuser
      POSTGRES_PASSWORD: traxpass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traxuser -d trax"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:
