version: "3.8"

services:
  app:
    build: .
    container_name: trax_lrs_app
    volumes:
      - .:/app
    ports:
      - "9000:9000"  # Pour PHP-FPM (interne)
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: trax
      DB_USERNAME: traxuser
      DB_PASSWORD: traxpass

  nginx:
    image: nginx:latest
    container_name: trax_lrs_nginx
    ports:
      - "8000:80"  # Expose vers l'extérieur
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15
    restart: always
    container_name: trax_lrs_db
    environment:
      POSTGRES_DB: trax
      POSTGRES_USER: traxuser
      POSTGRES_PASSWORD: traxpass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
